# 식당 정보 REST_INFO(REST_ID, REST_NAME, FOOD_TYPE, VIEWS, FAVORITES, PARKING_LOT, ADDRESS, TEL)
# 식당 리뷰 REST_REVIEW(REVIEW_ID, REST_ID FK, MEMBER_ID FK, REVIEW_SCORE, REVIEW_TEXT, REVIEW_DATE)

SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, REST_REVIEW.SCORE 
FROM REST_INFO
INNER JOIN (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) AS REST_REVIEW
ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
WHERE LEFT(ADDRESS, 2) = '서울' 
ORDER BY SCORE DESC, FAVORITES DESC