WITH A AS(
    SELECT WRITER_ID,
    SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS='DONE'
    GROUP BY WRITER_ID
)

SELECT USER_ID, NICKNAME, A.TOTAL_SALES
FROM USED_GOODS_USER
JOIN A
ON A.WRITER_ID = USED_GOODS_USER.USER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;