# ECOLI_DATA 
# PARENT_ID 부모 개체의 ID -> 부모 값이 없으면 이는 
# SIZE_OF_COLONY 개체의 크기
# DIFFERENTIATION_DATE 분화되어 나온 날짜
# GENOTYPE 개체의 형질

SELECT ID, 
(CASE 
    WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
    WHEN SIZE_OF_COLONY > 1000 THEN 'HIGH'
    ELSE 'MEDIUM'
END) AS SIZE
FROM ECOLI_DATA
ORDER BY ID ASC;