# ECOLI_DATA 
# PARENT_ID 부모 개체의 ID -> 부모 값이 없으면 이는 
# SIZE_OF_COLONY 개체의 크기
# DIFFERENTIATION_DATE 분화되어 나온 날짜
# GENOTYPE 개체의 형질
SELECT ID, IFNULL(CHILDS.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA
LEFT JOIN (
    SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) AS CHILDS
ON ECOLI_DATA.ID=CHILDS.PARENT_ID
ORDER BY ID ASC;
