# ECOLI_DATA 
# PARENT_ID 부모 개체의 ID -> 부모 값이 없으면 이는 
# SIZE_OF_COLONY 개체의 크기
# DIFFERENTIATION_DATE 분화되어 나온 날짜
# GENOTYPE 개체의 형질

SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE GENOTYPE & 2 = 0
AND (GENOTYPE & 1 > 0 OR GENOTYPE & 4 > 0);