# ECOLI_DATA 
# PARENT_ID 부모 개체의 ID -> 부모 값이 없으면 이는 
# SIZE_OF_COLONY 개체의 크기
# DIFFERENTIATION_DATE 분화되어 나온 날짜
# GENOTYPE 개체의 형질

# 자식이 부모의 형질을 모두 보유
#부모조회, 자식조회
SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS CHILD
JOIN ECOLI_DATA AS PARENT
ON PARENT.ID = CHILD.PARENT_ID
WHERE CHILD.GENOTYPE & PARENT.GENOTYPE = PARENT.GENOTYPE
ORDER BY CHILD.ID ASC