WITH TIER AS(
    SELECT ID, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS TILE
    FROM ECOLI_DATA
)

SELECT ECOLI_DATA.ID, 
(
    CASE
        WHEN TIER.TILE = 1 THEN 'CRITICAL'
        WHEN TIER.TILE = 2 THEN 'HIGH'
        WHEN TIER.TILE = 3 THEN 'MEDIUM'
        WHEN TIER.TILE = 4 THEN 'LOW'
    END
)AS COLONY_NAME
FROM ECOLI_DATA
JOIN TIER
ON ECOLI_DATA.ID = TIER.ID
ORDER BY ID ASC;